
select * from ciudad;
select * from ruta;

select * from CONTADOR;

sp_help ruta

SELECT ULTIMO FROM CONTADOR WHERE IDCONTADOR = 3

INSERT INTO CIUDAD(IDRUTA,NOMBRE,ORIGEN,DESTINO,DURACION,PRECIO1,PRECIO2,PRECIO3,IDEMPLEADO)
VALUES(?,?,?,?,?,?,?,?,?)

INSERT INTO CIUDAD(IDRUTA,NOMBRE,ORIGEN,DESTINO,DURACION,PRECIO1,PRECIO2,PRECIO3,IDEMPLEADO)
VALUES(?,?,?,?,?,?,?,?,?)

SELECT COUNT(1) FILAS FROM RUTA WHERE ORIGEN=? AND DESTINO=?

delete from ruta where IDRUTA=3;
