
CREATE TABLE EMPLEADO
( 
	IDEMPLEADO           integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	DISTRITO             varchar(60)  NOT NULL ,
	CORREO               varchar(60)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	ACTIVO               integer  NOT NULL 
	CONSTRAINT DF_EMPLEADO_ACTIVO
		 DEFAULT  1
	CONSTRAINT CK_EMPLEADO_ACTIVO
		CHECK  ( [ACTIVO]=0 OR [ACTIVO]=1 ),
	CONSTRAINT XPKEMPLEADO PRIMARY KEY (IDEMPLEADO ASC)
)
go



CREATE TABLE ROL
( 
	IDROL                integer  NOT NULL ,
	NOMBRE               varchar(60)  NOT NULL ,
	CONSTRAINT XPKROL PRIMARY KEY (IDROL ASC)
)
go



CREATE TABLE USUARIO
( 
	IDEMPLEADO           integer  NOT NULL ,
	USUARIO              varchar(60)  NOT NULL ,
	CLAVE                varchar(60)  NOT NULL ,
	IDROL                integer  NOT NULL ,
	ACTIVO               integer  NOT NULL 
	CONSTRAINT DF_USUARIO_ACTIVO
		 DEFAULT  1
	CONSTRAINT CK_USUARIO_ACTIVO
		CHECK  ( [ACTIVO]=0 OR [ACTIVO]=1 ),
	CONSTRAINT XPKUSUARIO PRIMARY KEY (IDEMPLEADO ASC),
	CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (IDROL) REFERENCES ROL(IDROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go


